### ISSUE TITLE
Don’t use primitive or vector master

### ISSUE THREAD

**Issue by cartazio** [haskell-vanguard/haskell-vanguard#2]

**Comment by cartazio** [comment]
Api stability or anything is not guaranteed for anything that isn’t a tagged release. 

Please use the tagged releases. I promise you someone is going to have a bad day otherwise

**Comment by cartazio** [comment]
primtivr 0.6.1.3 and whatever the recent thing I did for vector is. 

The git tags for both and at worst the hackage revision of the associated cabal file if I didn’t mutate the git tag are what you should pick

**Comment by fumieval** [comment]
Did you push primitive-0.6.1.3? I don't see it on https://github.com/haskell/primitive/tags

**Comment by cartazio** [comment]
Might be .2

I’ll double check. But whichever is the highest bug fix in the 0.6.1 series
on hackage should work fine on 8.8 out of the box. If I did a hackage
revision I’ll mutate the associated tag.  I know I did so with vector. (The
solver already Pickens the only one on hackage for both packages.or I need
to question reality  )

**Comment by fumieval** [comment]
The latest released version of aeson doesn't build with primitive-0.6.1.3; see https://github.com/bos/aeson/commit/aae9439be3f58d85025e8a54ba5dfc49eb53bb96

I checked primitive-0.6.1.2 on Hackage and it has base < 4.14, while on GitHub the upper bound is still 4.13.

**Comment by cartazio** [comment]
Is that a bogus constraint on the aeson side or what’s the cause there?

**Comment by fumieval** [comment]
It depends on Data.Primitive.SmallArray which is added in primitive-0.6.2.0.

**Comment by cartazio** [comment]
I did see that aeson has an unlifted array instance somewhere ... though
unlifted arrays aren’t really used anywhere in all of hackage

(I grepped a local copy of January hackage and only one person uses them
maybe two.  And their packages aren’t used by anyone else )

**Comment by fumieval** [comment]
Another problem is that the IsList instance for Array is missing. If we stick to primitive-0.6.1.2 and make the instances conditional, aeson is going to have a breaking change.

```
Data/Aeson/Types/FromJSON.hs:1931:20: error:
    • Could not deduce (Exts.IsList (PM.Array a))
        arising from a use of ‘Exts.fromList’
      from the context: FromJSON a
        bound by the instance declaration
        at Data/Aeson/Types/FromJSON.hs:1928:10-44
    • In the first argument of ‘fmap’, namely ‘Exts.fromList’
      In the first argument of ‘(.)’, namely ‘fmap Exts.fromList’
      In the expression: fmap Exts.fromList . parseJSON
     |
1931 |   parseJSON = fmap Exts.fromList . parseJSON
     |                    ^^^^^^^^^^^^^

Data/Aeson/Types/FromJSON.hs:1931:36: error:
    • Could not deduce (FromJSON (Exts.Item (PM.Array a)))
        arising from a use of ‘parseJSON’
      from the context: FromJSON a
        bound by the instance declaration
        at Data/Aeson/Types/FromJSON.hs:1928:10-44
    • In the second argument of ‘(.)’, namely ‘parseJSON’
      In the expression: fmap Exts.fromList . parseJSON
      In an equation for ‘parseJSON’:
          parseJSON = fmap Exts.fromList . parseJSON
     |
1931 |   parseJSON = fmap Exts.fromList . parseJSON
     |  
```

**Comment by cartazio** [comment]
Shit. Ok

Hrmm.

**Comment by cartazio** [comment]
I’ll do a back port on the 0.6.4 series we currently have on hackage then

The unlifted stuff I’m planning to split into a new package because it’s
not used much, but I’ll do a back portof the monad fall fixed onto
thecirrent hackage release

**Comment by cartazio** [comment]
I’ll also look at the change set of the aeson side.

I’d rather not have unlifted arrays leak into wider use in their current
form.  And next pass will  break all current forms.

**Comment by cartazio** [comment]
http://hackage.haskell.org/package/aeson-1.4.0.0
And older don’t have the primitive constraint.

**Comment by fumieval** [comment]
Rolling back to older aeson means no support for the latest `th-abstraction` (i.e. unbuildable on GHC 8.8).

**Comment by cartazio** [comment]
Huh. How does aeson and th-abstraction relate? I’ll hsve to look it up.

To be clear: I’ll see about doing the needed release later today, I just
wanna understand what build plan surgery alternatives exists.

**Comment by cartazio** [comment]
http://hackage.haskell.org/package/th-abstraction

I don’t see the connection..

**Comment by fumieval** [comment]
aeson has a TH-based deriving mechanism and it depends on th-abstraction.

**Comment by cartazio** [comment]
Then it should use it.

Nothing about that has to do with primitive ...
